      name: Build BuzzTube AAB (auto keystore)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.0"

      - name: Install deps
        run: |
          cd flutter_app
          flutter pub get

      # 🔑 Auto-generate upload keystore (first run). Reuse the same file for future updates.
      - name: Generate keystore
        run: |
          cd flutter_app/android/app
          keytool -genkey -v -keystore upload-keystore.jks -storepass 123456 -keypass 123456 -alias buzztube_key -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=BuzzTube, OU=BT, O=BT, L=City, S=State, C=IN"
          echo "storePassword=123456" > ../key.properties
          echo "keyPassword=123456" >> ../key.properties
          echo "keyAlias=buzztube_key" >> ../key.properties
          echo "storeFile=upload-keystore.jks" >> ../key.properties

      - name: Build AAB
        run: |
          cd flutter_app
          flutter build appbundle --release

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: flutter_app/build/app/outputs/bundle/release/app-release.aab

      - name: Upload Keystore artifact (download & keep safe)
        uses: actions/upload-artifact@v4
        with:
          name: upload-keystore
          path: flutter_app/android/app/upload-keystore.jks
